
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chengsheng?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    dbcp2:
      max-idle: 10
      max-total: 50
      max-wait-millis: 10000
      initial-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  freemarker:
    settings:
      number_format: 0.##

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder:

