
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/chengsheng?characterEncoding=utf8
    username: root
    password: 123
    dbcp2:
      max-idle: 10
      max-total: 50
      max-wait-millis: 10000
      initial-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
