server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://49.235.24.140:3306/chengsheng?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    dbcp2:
      max-idle: 10
      max-total: 50
      max-wait-millis: 10000
      initial-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  freemarker:
    settings:
      number_format: 0.##

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.chengsheng.logistics.entity


logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.chengsheng.logistics.business: debug

